/*
	This file contains all definitions for the JSON files. Right now, it's maintained manually.
	In the future, this file should be generated by the JSON schema files.
*/

export interface Bundeslaender {
	BW: Bundesland;
	BY: Bundesland;
	BE: Bundesland;
	BB: Bundesland;
	HB: Bundesland;
	HH: Bundesland;
	HE: Bundesland;
	MV: Bundesland;
	NI: Bundesland;
	NW: Bundesland;
	RP: Bundesland;
	SL: Bundesland;
	SN: Bundesland;
	ST: Bundesland;
	SH: Bundesland;
	TH: Bundesland;
}

export const BundeslandIDs = [
	"BW",
	"BY",
	"BE",
	"BB",
	"HB",
	"HH",
	"HE",
	"MV",
	"NI",
	"NW",
	"RP",
	"SL",
	"SN",
	"ST",
	"SH",
	"TH",
];

export interface Bundesland {
	land: string;
	gesundheit: Information;
	chef: Information;
	schule: Information;
}

export interface Information {
	bezeichnung: string;
	titel: string;
	name: string;
	mail: string;
	fax: string;
	anschrift: string[];
}

export interface CNAData {
	anrede: string[];
	gruss: string[];
	topics: Topic[];
}

export interface Topic {
	name: string;
	einleitung: WithCategory[];
	betreff: WithCategory[];
	beschwerde: WithCategory[];
	appell: WithCategory[];
}

export interface WithCategory {
	text: string;
	kategorie: string;
}
