/*
	This file contains all definitions for the JSON files. Right now, it's maintained manually.
	In the future, this file should be generated by the JSON schema files.
*/

export interface Bundeslaender {
	$schema: string;
	BUND: Bundesland;
}

export class Bundesland {
	land: string;
	onlyLimitedEntries?: boolean = false;
	kontakte: Information[];
}

export class Information {
	bezeichnung = "";
	titel = "";
	name = "";
	mail = "";
	fax = "";
	anschrift: string[] = [];
}

export class CNAData {
	anrede: string[] = [];
	gruss: string[] = [];
	topics: Topic[] = [];
}

export class Topic {
	name?: string;
	limit?: string[];
	einleitung: string[] = [];
	betreff: string[] = [];
	beschwerde: string[] = [];
	appell: string[] = [];
}

export type Receiver = {
	bezeichnung: string;
	titel: string;
	name: string;
	mail: string;
	fax: string;
	tel?: string;
	anschrift: string[];
	anreden?: string[];
};
